### ISSUE TITLE
is this still work for dsm62 and junboot103b?

### ISSUE THREAD

**Issue by laris** [segator/xpenology-docker#3]
I got failure.

https://xpenology.com/forum/topic/7884-xpenology-runing-on-docker/?do=findComment&comment=95335

**Comment by laris** [comment]
fixed for some kernel module in the post.
need to fix more.

**Comment by segator** [comment]
let me know if you finally got it working we should update the docker image.

**Comment by laris** [comment]
Thanks Segator,
9p work now, but looks like junboot 103b cannot boot dsm62 if use the bootloader img file as usb.

**Comment by laris** [comment]
looks like kvm also use the synoboot.img as usb disk, did you update to 6.2 ?
I create VM in proxmox but got mount failed error.

KVM_SYNOBOOT="-device ich9-usb-ehci1,id=usb,multifunction=on -drive file=/synoboot.img,format=raw,if=none,id=drive-usb-disk2,cache=writeback -device usb-storage,bus=usb.0,port=2,drive=drive-usb-disk2,id=usb-disk2,bootindex=1,removable=off"

**Comment by lost-carrier** [comment]
Hi @laris , hi @segator 

tried to update to ds3615xs/ds3617xs 1.03b and ds918p 1.04b today, but no success.

Not exactly sure, what your issue is, but I get just "mount failed" right after the grub screen.

The grub.cfg is patched to...
```
set vid=0x46f4
set pid=0x0001
```
...and so on, but still no luck.

Do you think this comment is relevant for us?
https://xpenology.com/forum/topic/12952-dsm-62-loader/?do=findComment&comment=93988

I'm using this line to attach the image to KVM
```
: ${KVM_DISK0_OPTS:="-drive file=/image/boot.img,format=raw,if=none,id=drive-sata0-0-1 -device ide-hd,drive=drive-sata0-0-1,id=sata0-0-1,bootindex=1"}
```
...so i guess it should already be mounted as SATA und RAW image appears still valid to me...

I'm not using 9P or something, so no special extra.lzma, right?

**Comment by lost-carrier** [comment]
Not sure if anyone is still reading this.

About that "mount failed" issues... I was finally successful to install ds3615xs with loader 1.03b and dsm 6.2-23739.

Settings are as follows:
```
: ${KVM_USB_OPTS:="\
	-device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x4.0x7 \
	-device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x4 \
	-device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x4.0x1 \
	-device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x4.0x2"}

: ${KVM_SATA_OPTS:="\
	-device ahci,id=sata0,bus=pci.0,addr=0x6 \
	-device ahci,id=sata1,bus=pci.0,addr=0x7"}

: ${KVM_DISK0_OPTS:="-drive file=/image/boot.img,format=raw,if=none,id=drive-usb-disk1 -device usb-storage,bus=usb.0,port=1,drive=drive-usb-disk1,id=usb-disk1,bootindex=1,removable=off"}
: ${KVM_DISK1_OPTS:="-drive file=/image/image,format=qcow2,if=none,id=drive-sata1-0-0 -device ide-hd,bus=sata1.0,drive=drive-sata1-0-0,id=sata1-0-0,bootindex=2"}
: ${KVM_BLK_OPTS:="$KVM_DISK0_OPTS $KVM_DISK1_OPTS"}
```
(derived from https://xpenology.com/forum/topic/13366-xpenology-on-kvmqemu/ and using USB instead of mounting synoboot.iso as IDE HDD)

IMPORTANT: Update to 6.2.1 fails since there were some changes to the pci kernel modules. As I read on the Xpenology forum only loader 1.04b (currently only available for ds918+) will properly handle this... (thou 1.03b *MIGHT* still work, too)

**Comment by T-REX-XP** [comment]
> Not sure if anyone is still reading this.
> 
> About that "mount failed" issues... I was finally successful to install ds3615xs with loader 1.03b and dsm 6.2-23739.
> 
> Settings are as follows:
> 
> ```
> : ${KVM_USB_OPTS:="\
> 	-device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x4.0x7 \
> 	-device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x4 \
> 	-device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x4.0x1 \
> 	-device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x4.0x2"}
> 
> : ${KVM_SATA_OPTS:="\
> 	-device ahci,id=sata0,bus=pci.0,addr=0x6 \
> 	-device ahci,id=sata1,bus=pci.0,addr=0x7"}
> 
> : ${KVM_DISK0_OPTS:="-drive file=/image/boot.img,format=raw,if=none,id=drive-usb-disk1 -device usb-storage,bus=usb.0,port=1,drive=drive-usb-disk1,id=usb-disk1,bootindex=1,removable=off"}
> : ${KVM_DISK1_OPTS:="-drive file=/image/image,format=qcow2,if=none,id=drive-sata1-0-0 -device ide-hd,bus=sata1.0,drive=drive-sata1-0-0,id=sata1-0-0,bootindex=2"}
> : ${KVM_BLK_OPTS:="$KVM_DISK0_OPTS $KVM_DISK1_OPTS"}
> ```
> 
> (derived from https://xpenology.com/forum/topic/13366-xpenology-on-kvmqemu/ and using USB instead of mounting synoboot.iso as IDE HDD)
> 
> IMPORTANT: Update to 6.2.1 fails since there were some changes to the pci kernel modules. As I read on the Xpenology forum only loader 1.04b (currently only available for ds918+) will properly handle this... (thou 1.03b _MIGHT_ still work, too)

Could you please share virtio compiled modules? I'm trying to use xpenology ds918 on Atomic Pi SBC.
but have a lot of problems: network and HDD are unavailable for setup.

Thanks

**Comment by segator** [comment]
I totally outdated about xpenology, I cannot help you anymore
